services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - pgadmin4_new
      - postgis_new
      - geodjango_tutorial

  pgadmin4_new:
    image: dpage/pgadmin4
    ports:
      - "20080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@docker.com
      PGADMIN_DEFAULT_PASSWORD: docker
    #volumes:
    #  - new_pgadmin4_data:/var/lib/postgresql/data

  postgis_new:
    image: kartoza/postgis
    ports:
      - 25432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gis
    #volumes:
    #  - my_first_spatialdb_data:/var/lib/postgresql/data

  geodjango_tutorial:
    image: geodjango_tutorial
    ports:
      - 8001:8001
    #build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    depends_on:
      - postgis_new