# Generated by Django 5.1.3 on 2025-01-02 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_book_userbooklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookList',
            new_name='UserBooks',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
